import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-blue-100 py-14">
          <div className="container mx-auto px-4">Header</div>
        </header>
        <main className="main-container">
          <div className="container mx-auto px-4">{children}</div>
        </main>
        <footer className="bg-blue-100 py-14">
          <div className="container mx-auto px-4">Footer</div>
        </footer>
      </body>
    </html>
  )
}
